server:
  port: 8888
spring:
  profiles:
    active:
      native
    cloud:
      config:
        server:
          native:
            searchLocations: file:/home/marco/IdeaProjects/microServices/confsvr/src/main/resources/config